<a href="https://colab.research.google.com/github/AlexBB999/Classwork/blob/master/17_6_RandomForestipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [25]:
# Load the Drive helper and mount
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
y2015=pd.read_csv('/content/drive/My Drive/LoanStats3d.csv',low_memory=False,skipinitialspace=True,header=1).copy()

In [0]:
y2015.head()

id   member_id  ...  total_bc_limit  total_il_high_credit_limit
0  68009401.0  72868139.0  ...        281300.0                     13400.0
1  68354783.0  73244544.0  ...         12500.0                     75635.0
2  68466916.0  73356753.0  ...         38400.0                     82117.0
3  68466961.0  73356799.0  ...         41500.0                     42503.0
4  68495092.0  73384866.0  ...          2750.0                     18248.0

[5 rows x 103 columns]

In [0]:
y2015.shape

(421097, 111)

###**The Blind Approach**

Now, as we've seen before, creating a model is the easy part. 
Let's try just using everything we've got and throwing it without much thought into a Random Forest.

 **SKLearn requires the independent variables to be be numeric**, and all we want is dummy variables **so let's use get_dummies** from Pandas to generate a dummy variable for every categorical column and see what happens off of this kind of naive approach.

In [0]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)

cross_val_score(rfc, X, Y, cv=5)

Did your kernel die? My kernel died.

Guess it isn't always going to be that easy...

Can you think of what went wrong?

(You're going to have to reset your kernel and reload the column, BUT DON'T RUN THE MODEL AGAIN OR YOU'LL CRASH THE KERNEL AGAIN!)

In [0]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


Well that right there is what's called a problem. 

**Some of these have over a hundred thousand distinct types**. 

Lets drop the ones with over 30 unique values, converting to numeric where it makes sense. In doing this there's a lot of code that gets written to just see if the numeric conversion makes sense. It's a manual process that we'll abstract away and just include the conversion.

You could extract numeric features from the dates, but here we'll just drop them.

 There's a lot of data, it shouldn't be a huge problem.

In [0]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

Wonder what was causing the dtype error on the id column, which should have all been integers? 

Let's look at the end of the file.

In [28]:
y2015.tail()

id   member_id  ...  total_bc_limit  total_il_high_credit_limit
421092  36271333.0  38982739.0  ...         10600.0                     33239.0
421093  36490806.0  39222577.0  ...          9700.0                     69919.0
421094  36271262.0  38982659.0  ...         41700.0                         0.0
421095         NaN         NaN  ...             NaN                         NaN
421096         NaN         NaN  ...             NaN                         NaN

[5 rows x 103 columns]

In [0]:
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]

In [0]:
y2015.head()

id   member_id  ...  total_bc_limit  total_il_high_credit_limit
0  68009401.0  72868139.0  ...        281300.0                     13400.0
1  68354783.0  73244544.0  ...         12500.0                     75635.0
2  68466916.0  73356753.0  ...         38400.0                     82117.0
3  68466961.0  73356799.0  ...         41500.0                     42503.0
4  68495092.0  73384866.0  ...          2750.0                     18248.0

[5 rows x 103 columns]

In [0]:
list(y2015)

['id',
 'member_id',
 'loan_amnt',
 'funded_amnt',
 'funded_amnt_inv',
 'term',
 'int_rate',
 'installment',
 'grade',
 'emp_length',
 'home_ownership',
 'annual_inc',
 'verification_status',
 'issue_d',
 'loan_status',
 'pymnt_plan',
 'purpose',
 'title',
 'dti',
 'delinq_2yrs',
 'inq_last_6mths',
 'mths_since_last_delinq',
 'mths_since_last_record',
 'open_acc',
 'pub_rec',
 'revol_bal',
 'total_acc',
 'initial_list_status',
 'out_prncp',
 'out_prncp_inv',
 'total_pymnt',
 'total_pymnt_inv',
 'total_rec_prncp',
 'total_rec_int',
 'total_rec_late_fee',
 'recoveries',
 'collection_recovery_fee',
 'last_pymnt_d',
 'last_pymnt_amnt',
 'next_pymnt_d',
 'last_credit_pull_d',
 'collections_12_mths_ex_med',
 'mths_since_last_major_derog',
 'policy_code',
 'application_type',
 'annual_inc_joint',
 'dti_joint',
 'verification_status_joint',
 'acc_now_delinq',
 'tot_coll_amt',
 'tot_cur_bal',
 'open_acc_6m',
 'open_il_6m',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'total_bal_il',


Now this should be better. Let's try again.

In [0]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
grade
7
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
purpose
14
title
27
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


In [0]:
y=pd.get_dummies(y2015)

In [0]:
y.shape

(421095, 237)

It finally works! We had to sacrifice sub grade, state address and description, but that's fine.

If you want to include them you could run the dummies independently and then append them back to the dataframe

**Second Attempt**

Now let's try this model again.

**We're also going to drop NA columns**, rather than impute, because our data is rich enough that we can probably get away with it.

This model may take a few minutes to run.

In [0]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

KeyboardInterrupt: ignored

**DRILL: Third Attempt**

**So here's your task**.

 **Get rid of as much data as possible without dropping below an average of 90% accuracy in a 10-fold cross validation**.

You'll want to do a few things in this process.
 First, dive into the data that we have and see which features are most important. 
 
 **This can be the raw features or the generated dummies**. 
 
 You may want to use PCA or correlation matrices.

**Can you do it without using anything related to payment amount or outstanding principal**?

 How do you know?

I STOPPEDMY CROSS VAL AFTER 20 MINUTES

**I WILL TRY IT AGAIN AFTER FURTHER FEATURE REDUCTION**

---



WILL DROP last_pymnt_d  AND last_credit_pull_d -- DROP 51 COLUMNS FROM DUMMY

In [0]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop(['loan_status','last_pymnt_d','last_credit_pull_d'], 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

KeyboardInterrupt: ignored

STILL TAKING FAR TOO LONG -- WILL ALSO DROP TITLE -- 27 MORE FEATURES

In [0]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop(['loan_status','last_pymnt_d','last_credit_pull_d','title'], 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

KeyboardInterrupt: ignored

STILL FAR TOO LONG --DROPPING PURPOSE -- 14 MORE FEATURES

In [0]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop(['loan_status','last_pymnt_d','last_credit_pull_d','title','purpose'], 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

KeyboardInterrupt: ignored

**THIS IS NUTS - I WILL SELECT 33% OF THE DATA FRAME TO SPEED THIS UP**

**ALSO DROP  issue_d**

**LOOKS LIKE I DROPPED TOO MUCH**

In [30]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop(['loan_status','last_pymnt_d','last_credit_pull_d','title','purpose','issue_d'], 1).sample(frac=1/3)
Y = y2015['loan_status'].sample(frac=1/3)
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.680701  , 0.68077224, 0.68048728, 0.680701  , 0.680701  ,
       0.68082075, 0.6807495 , 0.68089199, 0.68082075, 0.6807495 ])

**I WILL RESTORE PURPOSE -- VERY LITTLE IMPROVEMENT**

In [31]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop(['loan_status','last_pymnt_d','last_credit_pull_d','title','issue_d'], 1).sample(frac=1/3)
Y = y2015['loan_status'].sample(frac=1/3)
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.68469046, 0.68454798, 0.68461922, 0.68454798, 0.68454798,
       0.68473924, 0.68459675, 0.68473924, 0.68452551, 0.68452551])

**I WILL DROP PURPOSE AND RESTORE  LST_PYMNT_D**

**THIS IS EVEN WORSE - ENOUGH FOR NW ON MY SLOW COMPUTER**

In [34]:
X = y2015.drop(['loan_status','purpose','last_credit_pull_d','title','issue_d'], 1).sample(frac=1/3)
Y = y2015['loan_status'].sample(frac=1/3)
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

array([0.68148465, 0.68184085, 0.68148465, 0.68148465, 0.68162713,
       0.68160445, 0.68174694, 0.68167569, 0.68146195, 0.68167569])